import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Sidebar from '../components/Sidebar/Sidebar'
import styles from '../styles/Home.module.css'

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Yrkesprov</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.header}>
          
          <Navbar />
          <Sidebar />

          <div className={styles.content}>
            <h1 className={styles.h1}>About us</h1>
            <p className={styles.p}>Founded in 2013 as a humble Tumblr blog, Unsplash has grown into an industry-leading visual community. It’s become a source of inspiration for everyone from award-winning writers like Deepak Chopra to industry-titans like Apple, and millions of creators worldwide.</p>
          </div>

        </div>
      </main>

    </div>
  )
}
