import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Sidebar from '../components/Sidebar/Sidebar'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { send } from 'emailjs-com';

export default function Contact() {

const [toSend, setToSend] = useState({
    from_name: '',
    to_name: 'next.unsplash@gmail.com',
    message: '',
    reply_to: '',
  });

  const onSubmit = (e) => {
    e.preventDefault();
    console.log("hej")
        send(
            'service_si0kt3r',
            'template_7ovwalv',
            toSend,
            'BMRb4pYqqwtHTtWrU'
        )
        .then((response) => {
            console.log('SUCCESS!', response.status, response.text);
        })
        .catch((err) => {
            console.log('FAILED...', err);
        });
    };

  const handleChange = (e) => {
    setToSend({ ...toSend, [e.target.name]: e.target.value });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Yrkesprov</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.header}>
          
          <Navbar />
          <Sidebar />

          <div className={styles.content}>
            <h1 className={styles.h1}>Contact us</h1>

            <form onSubmit={onSubmit} className={styles.formClass}>
                <input
                  type='text'
                  name='from_name'
                  placeholder='From'
                  value={toSend.from_name}
                  onChange={handleChange}
                  className={styles.input}
                />
                <input
                  type='text'
                  name='message'
                  placeholder='Your message'
                  value={toSend.message}
                  onChange={handleChange}
                  className={styles.input}
                />
                <input
                  type='text'
                  name='reply_to'
                  placeholder='Your email'
                  value={toSend.reply_to}
                  onChange={handleChange}
                  className={styles.input}
                />
                <button type='submit' className={styles.submit}>Submit</button>
            </form>
          </div>

        </div>
      </main>

    </div>
  )
}
