import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Sidebar from '../components/Sidebar/Sidebar'
import styles from '../styles/Home.module.css'

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Yrkesprov</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.header}>
          
          <Navbar />
          <Sidebar />

          <div className={styles.content}>
            <h1 className={styles.h1}>What's New</h1>
            <p className={styles.p}>In March 2021, Unsplash was acquired by Getty Images for an undisclosed sum. Unsplash will continue to operate as a standalone brand and division of Getty Images with Cho in charge.</p>
          </div>

        </div>
      </main>

    </div>
  )
}
